const fs=require('fs');
const path=require('path');
const jwt=require('jsonwebtoken');
const {Pool}=require('pg');
const expressPath=require.resolve('express');
const originalExpress=require(expressPath);
const SECRET=()=>process.env.JWT_SECRET||'local-development-secret-change-me';
const DATA=path.join(__dirname,'attendance-data.json');
const production=!!process.env.DATABASE_URL;
const pool=production?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false,max:10}):null;
let dbReady=null;
function localLoad(){if(!fs.existsSync(DATA))return {admin:{id:1},employees:[],attendance:[],leaves:[],work_reports:[],holidays:[],cl_ledger:[]};const d=JSON.parse(fs.readFileSync(DATA,'utf8'));d.employees??=[];d.attendance??=[];d.leaves??=[];d.work_reports??=[];d.holidays??=[];d.cl_ledger??=[];return d}
function localSave(d){fs.writeFileSync(DATA,JSON.stringify(d,null,2))}
function nextId(a){return a.reduce((m,x)=>Math.max(m,Number(x.id)||0),0)+1}
function day(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function isSunday(date){return new Date(`${date}T00:00:00+05:30`).getDay()===0}
function auth(role){return(req,res,next)=>{try{const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!t)return res.sendStatus(401);const u=jwt.verify(t,SECRET());if(role&&u.role!==role)return res.sendStatus(403);req.user=u;next()}catch{res.sendStatus(401)}}}
async function ensureDb(){if(!production)return;if(!dbReady)dbReady=pool.query(`CREATE TABLE IF NOT EXISTS holidays(id SERIAL PRIMARY KEY,date DATE NOT NULL UNIQUE,name TEXT NOT NULL,type TEXT NOT NULL DEFAULT 'company' CHECK(type IN('public','company','office')),note TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS cl_ledger(id SERIAL PRIMARY KEY,employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,date DATE NOT NULL,reason TEXT NOT NULL,paid BOOLEAN NOT NULL DEFAULT FALSE,paid_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(employee_id,date));CREATE INDEX IF NOT EXISTS holidays_date_idx ON holidays(date);CREATE INDEX IF NOT EXISTS cl_employee_idx ON cl_ledger(employee_id);`);await dbReady}
async function holiday(date){await ensureDb();if(isSunday(date))return {date,name:'Sunday',type:'weekly'};if(!production)return localLoad().holidays.find(h=>h.date===date)||null;const r=await pool.query('SELECT * FROM holidays WHERE date=$1',[date]);return r.rows[0]||null}
async function awardCL(employeeId,date){const h=await holiday(date);if(!h)return false;await ensureDb();if(!production){const d=localLoad();if(d.cl_ledger.some(x=>Number(x.employee_id)===Number(employeeId)&&x.date===date))return false;d.cl_ledger.push({id:nextId(d.cl_ledger),employee_id:Number(employeeId),date,reason:h.name,paid:false,paid_at:null,created_at:new Date().toISOString()});localSave(d);return true}const r=await pool.query('INSERT INTO cl_ledger(employee_id,date,reason) VALUES($1,$2,$3) ON CONFLICT(employee_id,date) DO NOTHING RETURNING id',[employeeId,date,h.name]);return !!r.rowCount}
function setup(app){
  app.use((req,res,next)=>{if(req.path==='/api/employee/check-out'&&req.method==='POST'){const oldEnd=res.end.bind(res);res.end=(...args)=>{oldEnd(...args);const id=req.user?.id;if(id)awardCL(id,day()).catch(e=>console.error('CL award failed',e));};}next()});
  app.get('/api/office/holidays',auth(),async(req,res)=>{try{await ensureDb();let rows=production?(await pool.query('SELECT * FROM holidays ORDER BY date')).rows:localLoad().holidays.sort((a,b)=>String(a.date).localeCompare(String(b.date)));res.json({holidays:rows,weekly_holiday:'Sunday'})}catch{res.status(500).json({error:'Could not load holidays'})}});
  app.get('/api/employee/cl',auth('employee'),async(req,res)=>{try{await ensureDb();let rows;if(production)rows=(await pool.query('SELECT * FROM cl_ledger WHERE employee_id=$1 ORDER BY date DESC',[req.user.id])).rows;else rows=localLoad().cl_ledger.filter(x=>Number(x.employee_id)===Number(req.user.id)).sort((a,b)=>String(b.date).localeCompare(String(a.date)));res.json({balance:rows.filter(x=>!x.paid).length,total_earned:rows.length,total_paid:rows.filter(x=>x.paid).length,rows})}catch{res.status(500).json({error:'Could not load CL balance'})}});
  app.get('/api/admin/holidays',auth('admin'),async(req,res)=>{try{await ensureDb();let rows=production?(await pool.query('SELECT * FROM holidays ORDER BY date')).rows:localLoad().holidays.sort((a,b)=>String(a.date).localeCompare(String(b.date)));res.json({holidays:rows,weekly_holiday:'Sunday'})}catch{res.status(500).json({error:'Could not load holidays'})}});
  app.post('/api/admin/holidays',auth('admin'),async(req,res)=>{try{const date=String(req.body.date||'').trim(),name=String(req.body.name||'').trim(),type=['public','company','office'].includes(req.body.type)?req.body.type:'company',note=String(req.body.note||'').trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!name)return res.status(400).json({error:'Date and holiday name are required'});if(isSunday(date))return res.status(400).json({error:'Sunday is already the weekly holiday'});await ensureDb();if(!production){const d=localLoad();if(d.holidays.some(h=>h.date===date))return res.status(400).json({error:'Holiday already exists'});const h={id:nextId(d.holidays),date,name,type,note,created_at:new Date().toISOString()};d.holidays.push(h);localSave(d);return res.json({ok:true,holiday:h})}const r=await pool.query('INSERT INTO holidays(date,name,type,note) VALUES($1,$2,$3,$4) ON CONFLICT(date) DO NOTHING RETURNING *',[date,name,type,note]);if(!r.rowCount)return res.status(400).json({error:'Holiday already exists'});res.json({ok:true,holiday:r.rows[0]})}catch{res.status(500).json({error:'Could not add holiday'})}});
  app.patch('/api/admin/holidays/:id',auth('admin'),async(req,res)=>{try{const id=Number(req.params.id),name=String(req.body.name||'').trim(),type=['public','company','office'].includes(req.body.type)?req.body.type:'company',note=String(req.body.note||'').trim();if(!name)return res.status(400).json({error:'Holiday name is required'});await ensureDb();if(!production){const d=localLoad(),h=d.holidays.find(x=>Number(x.id)===id);if(!h)return res.sendStatus(404);Object.assign(h,{name,type,note});localSave(d);return res.json({ok:true})}const r=await pool.query('UPDATE holidays SET name=$1,type=$2,note=$3 WHERE id=$4 RETURNING id',[name,type,note,id]);if(!r.rowCount)return res.sendStatus(404);res.json({ok:true})}catch{res.status(500).json({error:'Could not update holiday'})}});
  app.delete('/api/admin/holidays/:id',auth('admin'),async(req,res)=>{try{const id=Number(req.params.id);await ensureDb();if(!production){const d=localLoad(),i=d.holidays.findIndex(x=>Number(x.id)===id);if(i<0)return res.sendStatus(404);d.holidays.splice(i,1);localSave(d);return res.json({ok:true})}const r=await pool.query('DELETE FROM holidays WHERE id=$1 RETURNING id',[id]);if(!r.rowCount)return res.sendStatus(404);res.json({ok:true})}catch{res.status(500).json({error:'Could not delete holiday'})}});
  app.get('/api/admin/cl',auth('admin'),async(req,res)=>{try{await ensureDb();let rows;if(production)rows=(await pool.query('SELECT c.*,e.name employee_name,e.email employee_email,e.phone employee_phone FROM cl_ledger c JOIN employees e ON e.id=c.employee_id ORDER BY c.date DESC,e.name')).rows;else{const d=localLoad();rows=d.cl_ledger.map(c=>{const e=d.employees.find(x=>Number(x.id)===Number(c.employee_id))||{};return {...c,employee_name:e.name||'Unknown',employee_email:e.email||'',employee_phone:e.phone||''}}).sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(a.employee_name).localeCompare(String(b.employee_name)))}const grouped={};for(const r of rows){grouped[r.employee_id]??={employee_id:r.employee_id,employee_name:r.employee_name,employee_email:r.employee_email,employee_phone:r.employee_phone,earned:0,paid:0,balance:0};grouped[r.employee_id].earned++;if(r.paid)grouped[r.employee_id].paid++;grouped[r.employee_id].balance=grouped[r.employee_id].earned-grouped[r.employee_id].paid}res.json({rows,summary:Object.values(grouped)})}catch{res.status(500).json({error:'Could not load CL records'})}});
  app.patch('/api/admin/cl/:id',auth('admin'),async(req,res)=>{try{const id=Number(req.params.id),paid=!!req.body.paid;await ensureDb();if(!production){const d=localLoad(),r=d.cl_ledger.find(x=>Number(x.id)===id);if(!r)return res.sendStatus(404);r.paid=paid;r.paid_at=paid?new Date().toISOString():null;localSave(d);return res.json({ok:true})}const q=await pool.query('UPDATE cl_ledger SET paid=$1,paid_at=$2 WHERE id=$3 RETURNING id',[paid,paid?new Date().toISOString():null,id]);if(!q.rowCount)return res.sendStatus(404);res.json({ok:true})}catch{res.status(500).json({error:'Could not update CL record'})}});
}
function wrappedExpress(...args){const app=originalExpress(...args);setup(app);return app}
Object.assign(wrappedExpress,originalExpress);
require.cache[expressPath].exports=wrappedExpress;
require('./work-server.js');
