const fs=require('fs'),path=require('path'),jwt=require('jsonwebtoken'),{Pool}=require('pg');
const expressPath=require.resolve('express'),baseExpress=require(expressPath);const SECRET=()=>process.env.JWT_SECRET||'local-development-secret-change-me';const production=!!process.env.DATABASE_URL;const DATA=path.join(__dirname,'attendance-data.json');const pool=production?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false,max:10}):null;let ready=null;
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const sunday=d=>new Date(`${d}T00:00:00+05:30`).getDay()===0;
const local=()=>{if(!fs.existsSync(DATA))return {admin:{id:1},employees:[],attendance:[],leaves:[],work_reports:[],holidays:[],cl_ledger:[]};const d=JSON.parse(fs.readFileSync(DATA,'utf8'));d.employees??=[];d.attendance??=[];d.leaves??=[];d.work_reports??=[];d.holidays??=[];d.cl_ledger??=[];return d};const save=d=>fs.writeFileSync(DATA,JSON.stringify(d,null,2));const next=a=>a.reduce((m,x)=>Math.max(m,Number(x.id)||0),0)+1;
function auth(role){return(req,res,nextFn)=>{try{const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const u=jwt.verify(t,SECRET());if(role&&u.role!==role)return res.sendStatus(403);req.user=u;nextFn()}catch{res.sendStatus(401)}}}
async function db(){if(!production)return;if(!ready)ready=pool.query(`CREATE TABLE IF NOT EXISTS holidays(id SERIAL PRIMARY KEY,date DATE UNIQUE NOT NULL,name TEXT NOT NULL,type TEXT NOT NULL DEFAULT 'company',note TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS cl_ledger(id SERIAL PRIMARY KEY,employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,date DATE NOT NULL,reason TEXT NOT NULL,paid BOOLEAN NOT NULL DEFAULT FALSE,paid_at TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT NOW(),UNIQUE(employee_id,date));`);await ready}
async function getHoliday(date){await db();if(sunday(date))return {date,name:'Sunday',type:'weekly'};if(!production)return local().holidays.find(x=>x.date===date)||null;const r=await pool.query('SELECT * FROM holidays WHERE date=$1',[date]);return r.rows[0]||null}
async function award(id,date){const h=await getHoliday(date);if(!h)return;await db();if(!production){const d=local();if(d.cl_ledger.some(x=>Number(x.employee_id)===Number(id)&&x.date===date))return;d.cl_ledger.push({id:next(d.cl_ledger),employee_id:Number(id),date,reason:h.name,paid:false,paid_at:null,created_at:new Date().toISOString()});save(d);return}await pool.query('INSERT INTO cl_ledger(employee_id,date,reason) VALUES($1,$2,$3) ON CONFLICT(employee_id,date) DO NOTHING',[id,date,h.name])}
function setup(app){
 app.use((req,res,nextFn)=>{if(req.path==='/api/employee/check-out'&&req.method==='POST'){try{const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const u=jwt.verify(t,SECRET());if(u.role==='employee')setTimeout(async()=>{try{let checked=false;if(!production){const d=local();checked=d.attendance.some(a=>Number(a.employee_id)===Number(u.id)&&a.date===today()&&a.check_out)}else{const r=await pool.query('SELECT id FROM attendance WHERE employee_id=$1 AND date=$2 AND check_out IS NOT NULL LIMIT 1',[u.id,today()]);checked=!!r.rowCount}if(checked)await award(u.id,today())}catch(e){console.error('CL award failed',e.message)}},700)}catch{} }nextFn()});
 app.use((req,res,nextFn)=>{if(req.method==='POST'&&req.path==='/api/admin/employees'){const p=req.body||{};if(p.password&&!strong(p.password))return res.status(400).json({error:'Password must be at least 8 characters and include uppercase, lowercase, number and symbol.'})}nextFn()});
 app.get('/api/office/holidays',auth(),async(req,res)=>{try{await db();const rows=production?(await pool.query('SELECT * FROM holidays ORDER BY date')).rows:local().holidays.sort((a,b)=>String(a.date).localeCompare(String(b.date)));res.json({weekly_holiday:'Sunday',holidays:rows})}catch{res.status(500).json({error:'Could not load holidays'})}});
 app.get('/api/employee/cl',auth('employee'),async(req,res)=>{try{await db();const rows=production?(await pool.query('SELECT * FROM cl_ledger WHERE employee_id=$1 ORDER BY date DESC',[req.user.id])).rows:local().cl_ledger.filter(x=>Number(x.employee_id)===Number(req.user.id)).sort((a,b)=>String(b.date).localeCompare(String(a.date)));res.json({balance:rows.filter(x=>!x.paid).length,total_earned:rows.length,total_paid:rows.filter(x=>x.paid).length,rows})}catch{res.status(500).json({error:'Could not load CL'})}});
 app.get('/api/admin/holidays',auth('admin'),async(req,res)=>{try{await db();const rows=production?(await pool.query('SELECT * FROM holidays ORDER BY date')).rows:local().holidays.sort((a,b)=>String(a.date).localeCompare(String(b.date)));res.json({weekly_holiday:'Sunday',holidays:rows})}catch{res.status(500).json({error:'Could not load holidays'})}});
 app.post('/api/admin/holidays',auth('admin'),async(req,res)=>{try{const date=String(req.body.date||''),name=String(req.body.name||'').trim(),type=['public','company','office'].includes(req.body.type)?req.body.type:'company',note=String(req.body.note||'').trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!name)return res.status(400).json({error:'Date and holiday name are required'});if(sunday(date))return res.status(400).json({error:'Sunday is already the weekly holiday'});await db();if(!production){const d=local();if(d.holidays.some(x=>x.date===date))return res.status(400).json({error:'Holiday already exists'});const h={id:next(d.holidays),date,name,type,note,created_at:new Date().toISOString()};d.holidays.push(h);save(d);return res.json({ok:true,holiday:h})}const r=await pool.query('INSERT INTO holidays(date,name,type,note) VALUES($1,$2,$3,$4) ON CONFLICT(date) DO NOTHING RETURNING *',[date,name,type,note]);if(!r.rowCount)return res.status(400).json({error:'Holiday already exists'});res.json({ok:true,holiday:r.rows[0]})}catch{res.status(500).json({error:'Could not add holiday'})}});
 app.delete('/api/admin/holidays/:id',auth('admin'),async(req,res)=>{try{const id=Number(req.params.id);await db();if(!production){const d=local(),i=d.holidays.findIndex(x=>Number(x.id)===id);if(i<0)return res.sendStatus(404);d.holidays.splice(i,1);save(d);return res.json({ok:true})}const r=await pool.query('DELETE FROM holidays WHERE id=$1 RETURNING id',[id]);if(!r.rowCount)return res.sendStatus(404);res.json({ok:true})}catch{res.status(500).json({error:'Could not delete holiday'})}});
 app.get('/api/admin/cl',auth('admin'),async(req,res)=>{try{await db();let rows;if(production)rows=(await pool.query('SELECT c.*,e.name employee_name,e.email employee_email,e.phone employee_phone FROM cl_ledger c JOIN employees e ON e.id=c.employee_id ORDER BY c.date DESC,e.name')).rows;else{const d=local();rows=d.cl_ledger.map(c=>{const e=d.employees.find(x=>Number(x.id)===Number(c.employee_id))||{};return {...c,employee_name:e.name||'Unknown',employee_email:e.email||'',employee_phone:e.phone||''}})}const s={};rows.forEach(r=>{s[r.employee_id]??={employee_id:r.employee_id,employee_name:r.employee_name,employee_email:r.employee_email,employee_phone:r.employee_phone,earned:0,paid:0,balance:0};s[r.employee_id].earned++;if(r.paid)s[r.employee_id].paid++;s[r.employee_id].balance=s[r.employee_id].earned-s[r.employee_id].paid});res.json({rows,summary:Object.values(s)})}catch{res.status(500).json({error:'Could not load CL records'})}});
 app.patch('/api/admin/cl/:id',auth('admin'),async(req,res)=>{try{const id=Number(req.params.id),paid=!!req.body.paid;await db();if(!production){const d=local(),r=d.cl_ledger.find(x=>Number(x.id)===id);if(!r)return res.sendStatus(404);r.paid=paid;r.paid_at=paid?new Date().toISOString():null;save(d);return res.json({ok:true})}const q=await pool.query('UPDATE cl_ledger SET paid=$1,paid_at=$2 WHERE id=$3 RETURNING id',[paid,paid?new Date().toISOString():null,id]);if(!q.rowCount)return res.sendStatus(404);res.json({ok:true})}catch{res.status(500).json({error:'Could not update CL record'})}});
}
function strong(p){return typeof p==='string'&&p.length>=8&&/[A-Z]/.test(p)&&/[a-z]/.test(p)&&/\d/.test(p)&&/[^A-Za-z0-9]/.test(p)}
function wrappedExpress(...args){const app=baseExpress(...args);setup(app);return app}Object.assign(wrappedExpress,baseExpress);require.cache[expressPath].exports=wrappedExpress;require('./work-server.js');
